### ISSUE TITLE
Model crashes / Paneron error

### ISSUE THREAD

**Issue by odeclas** [paneron/extension-hls#33] opened 2021-09-29 11:19 UTC
I don't know if it's simply because not all tool options are available in all models or some other reason, but when switching between model files in Paneron using extension HLS for demo purposes I often find it crashes.

I'm typically using PAS2060, iso13485, bs202000, bs16341 and bs20400 to demonstrate things with. I'll try to grab a screenshot next time.

**Comment by wkwong-ribose** [comment] 2021-09-30 07:54
I am not able to reproduce the problem now. Maybe it is related to the functions/tools you were using before switching the models. If @odeclas can tell me which functions you were using before the crash, it may help.
 
I will remove PAS2060 in the folder. Please use the ones in the geo folder.

**Comment by odeclas** [comment] 2021-10-04 09:01
Ok, appreciate that a vague crash report is not helpful, but I think only PAS2060 demonstrates Measurement test. The problem in being specific is that it usually crashes in a live demo, and I have to move on rather than note what I was doing....

**Comment by wkwong-ribose** [comment] 2021-10-05 00:02
Maybe I was not clear in my last comment. The file "PAS 2060.mmel" is an old version using an outdated MMEL data structure. The outdated data structure may be a reason causing the crash. The updated versions of PAS 2060 can be found in the geo folder (https://github.com/metanorma/mmel-models/tree/main/geo). There is a tiny dashboard for PAS 2060 too, that makes use of the measurement test function.
  
<img width="1264" alt="Screen Shot 2021-10-05 at 7 56 07 AM" src="https://user-images.githubusercontent.com/80878223/135939860-faa8f736-0647-4366-b743-b5189b359f53.png">
 
To avoid confusion on the versions of PAS2060, I removed the outdated file from the repo. The files in the geo folder are the up-to-date versions of PAS2060.
PAS 2060 original.mmel --- the basic one without the dashboard
PAS2060 with plugin.mmel --- with the dashboard
PAS 2060 extended with plugin.mmel --- example extended model adding a custom test to the standard

**Comment by odeclas** [comment] 2021-10-05 13:36
What reference URL for the sensor readings source do I need to add for the PAS 2060 - I can't replicate the above dashboard exactly (I have worked out to add the buildings).

**Comment by wkwong-ribose** [comment] 2021-10-06 01:50
I will update the extension later so that you can use "localhost:2060" to generate synthetic data for the dashboard.
The update will also include the quick-edit mode of all components in the model.
You can view a reference model while editing. Importing a component from another model is now done by drag-and-drop. The importing logic is fixed now.
You can open a document in edit model, select some text, click a button and make it a provision.
<img width="1392" alt="Screen Shot 2021-10-06 at 9 48 39 AM" src="https://user-images.githubusercontent.com/80878223/136127896-f9241d6c-8603-4e1f-8f8b-5270e63b3c12.png">

The update is expected to be ready today or tomorrow.

**Comment by wkwong-ribose** [comment] 2021-10-08 09:04
Found a bug that may be relevant.
If you change the model while the document filtering setting is set to non-empty in provision summary, the extension crashes as it tries to load the list of clauses in the new model which do not exist.
It is fixed in a recent update.

Here is the updated extension package.

[extension 8 Oct 2021.zip](https://github.com/paneron/extension-hls/files/7309972/extension.8.Oct.2021.zip)

**Closed** 2021-11-15 04:14 UTC
